# Generated by Django 5.1.1 on 2024-10-06 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id_actor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id_director', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id_pelicula', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('productora', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateField()),
                ('id_director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Alquiler.director')),
            ],
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id_ejemplar', models.AutoField(primary_key=True, serialize=False)),
                ('estado_conservacion', models.CharField(max_length=50)),
                ('id_pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alquiler.pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('dni', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('avalado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaladores', to='Alquiler.socio')),
            ],
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id_alquiler', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_comienzo', models.DateField()),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('id_ejemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alquiler.ejemplar')),
                ('dni_socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alquiler.socio')),
            ],
        ),
        migrations.CreateModel(
            name='PeliculaActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.BooleanField(default=False)),
                ('id_actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alquiler.actor')),
                ('id_pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alquiler.pelicula')),
            ],
            options={
                'unique_together': {('id_pelicula', 'id_actor')},
            },
        ),
    ]
